site_url: https://frischmuth-frontend-dev.acdh-ch-dev.oeaw.ac.at/
logo_url: /icon.svg
load_config_file: true
local_backend: true
backend:
  name: github
  repo: acdh-oeaw/frischmuth-frontend
  branch: dev
  base_url: https://frischmuth-frontend-dev.acdh-ch-dev.oeaw.ac.at/
  auth_endpoint: /api/oauth/authorize
  auth_scope: repo
  squash_merges: true
  commit_messages:
    create: "content(create): {{collection}} '{{slug}}'"
    update: "content(update): {{collection}} '{{slug}}'"
    delete: "content(delete): {{collection}} '{{slug}}'"
    uploadMedia: "content(upload): '{{path}}'"
    deleteMedia: "content(delete): '{{path}}'"
# publish_mode: editorial_workflow
media_folder: /public/assets/images
public_folder: /assets/images
editor:
  preview: false
collections:
  - name: about
    label: Über das Projekt
    label_singular: Über das Projekt
    # description: Pages
    folder: content/pages/about
    create: false
    delete: false
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: Title
        # hint: The title

      - name: sections
        label: Sections
        # hint: The content
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Content
            name: content
            widget: markdown
            modes:
              # - raw
              - rich_text
  - name: academic-reception
    label: Akademische Rezeption
    label_singular: Akademische Rezeption
    # description: Pages
    folder: content/pages/academic-reception
    create: false
    delete: false
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: Title
        # hint: The title

      - name: sections
        label: Sections
        # hint: The content
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Content
            name: content
            widget: markdown
            modes:
              # - raw
              - rich_text
  - name: journalistic-reception
    label: Journalistische Rezeption
    label_singular: Journalistische Rezeption
    # description: Pages
    folder: content/pages/journalistic-reception
    create: false
    delete: false
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: Title
        # hint: The title

      - name: sections
        label: Sections
        # hint: The content
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Content
            name: content
            widget: markdown
            modes:
              # - raw
              - rich_text
  - name: autobiografiction
    label: Autobiografiktion
    label_singular: Autobiografiktion
    # description: Pages
    folder: content/pages/autobiografiction
    create: false
    delete: false
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: Title
        # hint: The title

      - name: sections
        label: Sections
        # hint: The content
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Content
            name: content
            widget: markdown
            modes:
              # - raw
              - rich_text
  - name: from-the-archive
    label: Aus dem Archiv
    label_singular: Aus dem Archiv
    # description: Pages
    folder: content/pages/from-the-archive
    create: false
    delete: false
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: Title
        # hint: The title

      - name: sections
        label: Sections
        # hint: The content
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Content
            name: content
            widget: markdown
            modes:
              # - raw
              - rich_text
  - name: places
    label: Orte-Intro
    label_singular: Orte-Intro
    # description: Pages
    folder: content/pages/places
    create: false
    delete: false
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: Title
        # hint: The title

      - name: body
        label: Content
        i18n: true
        # hint: The content
        widget: markdown
        modes:
          # - raw
          - rich_text
  - name: themes
    label: Themen-Intro
    label_singular: Themen-Intro
    # description: Pages
    folder: content/pages/themes
    create: false
    delete: false
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: Title
        # hint: The title

      - name: body
        label: Content
        i18n: true
        # hint: The content
        widget: markdown
        modes:
          # - raw
          - rich_text
  - name: research-aspects
    label: Forschungshinsichten-Intro
    label_singular: Forschungshinsichten-Intro
    # description: Pages
    folder: content/pages/research-aspects
    create: false
    delete: false
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: Title
        # hint: The title

      - name: body
        label: Content
        i18n: true
        # hint: The content
        widget: markdown
        modes:
          # - raw
          - rich_text
  - name: glossary
    label: Glossar-Intro
    label_singular: Glossar-Intro
    # description: Pages
    folder: content/pages/glossary
    create: false
    delete: false
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: Title
        # hint: The title

      - name: body
        label: Content
        i18n: true
        # hint: The content
        widget: markdown
        modes:
          # - raw
          - rich_text
  - name: biography
    label: Biografie-Einträge
    label_singular: Biografie-Einträge
    # description: Biography entries for the biography-page.
    folder: content/pages/biography
    identifier_field: year
    create: true
    delete: true
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: year
        label: Year
        widget: string
        required: true

      - name: image
        label: Image
        # hint: The image
        widget: image
        required: false

      - name: imageTitle
        label: Image Title
        widget: string
        hint: The title will be displayed next to the image
        required: false

      - name: alt
        label: Alt
        widget: string
        hint:
          The alt will not be displayed, it should describe the image. If not provided the title of
          the image will be the alt.
        required: false

      - name: copyright
        label: Copyright
        widget: string
        hint: The copyright if provided will be displayed under the title
        required: false

      - name: body
        label: Content
        hint: The short biography
        widget: markdown
        modes:
          # - raw
          - rich_text
  - name: altaussee-page
    label: Altaussee-Text
    label_singular: Altaussee-sText
    # description: Pages
    folder: content/pages/altaussee/text
    create: false
    delete: false
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: Title
        # hint: The title

      - name: sections
        label: Sections
        # hint: The content
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Content
            name: content
            widget: markdown
            modes:
              # - raw
              - rich_text
  - name: altausseePlaces
    label: Altaussee-Orte
    label_singular: Altaussee-Orte
    # description: Biography entries for the biography-page.
    folder: content/pages/altaussee/places
    create: true
    delete: true
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: Ortsname
        widget: string
        required: true

      - name: coordinates
        label: Coordinates
        widget: object
        fields:
          - name: latitude
            label: Latitude
            widget: number
            value_type: float
            required: true
          - name: longitude
            label: Longitude
            widget: number
            value_type: float
            required: true

      - name: images
        label: Images
        widget: list
        required: false
        allow_add: true
        fields:
          - name: titel
            label: Image Title
            widget: string
            required: true
          - name: image
            label: Image
            widget: image
            required: true
          - name: alt
            label: Alt
            widget: string
            hint:
              The alt will not be displayed, it should describe the image. If not provided the title
              of the image will be the alt.
            required: false
          - name: copyright
            label: Copyright
            widget: string
            hint: The copyright if provided will be displayed under the title
            required: false

      - name: body
        label: Description
        widget: markdown
        modes:
          # - raw
          - rich_text
      - name: links
        label: Links to related works
        widget: list
        allow_add: true
        fields:
          - name: workTitle
            label: Work Title
            widget: string
            required: true
          - name: url
            label: URL
            widget: string
            required: true
  - name: quotes
    label: Zitate
    label_singular: Zitate
    # description: Quotes for the explore page.
    folder: content/pages/quotes
    create: true
    delete: true
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: title
        hint: For recognition in the cms.
        widget: string
        required: true

      - name: link
        label: Link to the related work
        # hint: Provide the plain link-text, not link it here.
        widget: string
        required: false

      - name: body
        label: Quote
        widget: markdown
        modes:
          # - raw
          - rich_text
  - name: exploreImages
    label: Entdecken-Kachel-Bilder
    label_singular: Entdecken-Kachel-Bilder
    # description: Quotes for the explore page.
    folder: content/pages/explore-images
    create: false
    delete: false
    # nested:
    #   depth: 3
    # meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
    fields:
      - name: title
        label: title
        hint: For recognition in the cms.
        widget: string
        required: true
      - name: images
        label: Explore-Kachel-Bilder
        widget: list
        required: true
        allow_add: true
        fields:
          - name: titel
            label: Image Title
            widget: string
            required: true
          - name: image
            label: Image
            widget: image
            required: true
          - name: alt
            label: Alt
            widget: string
            hint:
              The alt will not be displayed, it should describe the image. If not provided the title
              of the image will be the alt.
            required: false
          - name: copyright
            label: Copyright
            widget: string
            hint: The copyright if provided will be displayed under the title
            required: false
